apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: hackathon-banner
spec:
  text: Welcome to the Argo CD managed Green Team OpenShift cluster for the Summit Connect Hackathon!
  location: BannerTop 
  link:
    href: 'https://github.com/ArctiqTeam/openshift-automation-example'
    text: (Check code to deploy and configure OpenShift on GCP automatiocally)
  color: '#fafafa'
  backgroundColor: '#16a34a'
